#!/bin/bash

port=$2
origin=$4
name=$6
username=$8
keyfile=${@: -1:1}
ipfile="./hosts/nodes.txt"
remotepath="cdn/"
dnsserv="cs5700cdnproject.ccs.neu.edu"

filelines=`cat $ipfile`

for line in $filelines
do
    ip=$line
    echo "Killing all $username processes @ $ip"
    ssh -i $keyfile $username@$ip "killall -user $username; exit"
done

echo "Killing all $username processes @ $dnsserv"
ssh -i $keyfile $username@$dnsserv "killall -user $username; exit"

echo "All servers down"
